In [1]:
import numpy as np
import pandas as pd

np.random.seed(123)

n_samples=1000
class_0_ratio=0.9
n_class_0=int(n_samples*class_0_ratio)
n_class_1=n_samples - n_class_0

In [2]:
n_class_0,n_class_1

(900, 100)

In [3]:
class_0=pd.DataFrame({
    'feature_1' : np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2' : np.random.normal(loc=0, scale=1, size=n_class_0),
    'target' : [0]*n_class_0
})

class_1=pd.DataFrame({
    'feature_1' : np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2' : np.random.normal(loc=2, scale=1, size=n_class_1),
    'target' : [1]*n_class_1
})

In [4]:
df=pd.concat([class_0,class_1]).reset_index(drop=True)

In [22]:
df.head()

   feature_1  feature_2  target
0  -1.085631   0.551302       0
1   0.997345   0.419589       0
2   0.282978   1.815652       0
3  -1.506295  -0.252750       0
4  -0.578600  -0.292004       0

In [8]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [23]:
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [30]:
from sklearn.utils import resample
df_minority_upsampled=resample(df_minority,replace=True,
                               n_samples=len(df_majority),
                               random_state=42
                               )

In [31]:
df_minority_upsampled.shape

(900, 3)

In [32]:
df_minority_upsampled.head()

     feature_1  feature_2  target
951   1.125854   1.843917       1
992   2.196570   1.397425       1
914   1.932170   2.998053       1
971   2.272825   3.034197       1
960   2.870056   1.550485       1

In [33]:
df_upsampled=pd.concat([df_majority,df_minority_upsampled])

In [35]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

In [36]:
import numpy as np
import pandas as pd

np.random.seed(123)

n_samples=1000
class_0_ratio=0.9
n_class_0=int(n_samples*class_0_ratio)
n_class_1=n_samples - n_class_0

class_0=pd.DataFrame({
    'feature_1' : np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2' : np.random.normal(loc=0, scale=1, size=n_class_0),
    'target' : [0]*n_class_0
})

class_1=pd.DataFrame({
    'feature_1' : np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2' : np.random.normal(loc=2, scale=1, size=n_class_1),
    'target' : [1]*n_class_1
})

df=pd.concat([class_0,class_1]).reset_index(drop=True)

df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [37]:
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [38]:
from sklearn.utils import resample
df_majority_downsampled=resample(df_majority,replace=False,
                               n_samples=len(df_minority),
                               random_state=42
                               )

In [39]:
df_majority_downsampled.shape

(100, 3)

In [40]:
df_downsampled=pd.concat([df_majority_downsampled,df_minority])

In [41]:
df_downsampled['target'].value_counts()

target
0    100
1    100
Name: count, dtype: int64